config/routes.rb
Rails.application.routes.draw do
  resources :pontuacaos
  resources :rodadas
  resources :cartoleiros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'rodadas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cartoleiro.rb
class Cartoleiro < ApplicationRecord
    has_many :pontuacaos
    has_many :rodadas, through: :pontuacaos
end

app/models/pontuacao.rb
class Pontuacao < ApplicationRecord
    belongs_to :cartoleiro
    belongs_to :rodada
end

app/models/rodada.rb
class Rodada < ApplicationRecord
    has_many :pontuacaos
    has_many :cartoleiros, through: :pontuacaos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/cartoleiros_controller.rb
class CartoleirosController < ApplicationController
  before_action :set_cartoleiro, only: %i[ show edit update destroy ]

  # GET /cartoleiros or /cartoleiros.json
  def index
    @cartoleiros = Cartoleiro.all
  end

  # GET /cartoleiros/1 or /cartoleiros/1.json
  def show
  end

  # GET /cartoleiros/new
  def new
    @cartoleiro = Cartoleiro.new
  end

  # GET /cartoleiros/1/edit
  def edit
  end

  # POST /cartoleiros or /cartoleiros.json
  def create
    @cartoleiro = Cartoleiro.new(cartoleiro_params)

    respond_to do |format|
      if @cartoleiro.save
        format.html { redirect_to cartoleiro_url(@cartoleiro), notice: "Cartoleiro was successfully created." }
        format.json { render :show, status: :created, location: @cartoleiro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cartoleiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartoleiros/1 or /cartoleiros/1.json
  def update
    respond_to do |format|
      if @cartoleiro.update(cartoleiro_params)
        format.html { redirect_to cartoleiro_url(@cartoleiro), notice: "Cartoleiro was successfully updated." }
        format.json { render :show, status: :ok, location: @cartoleiro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cartoleiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartoleiros/1 or /cartoleiros/1.json
  def destroy
    @cartoleiro.destroy

    respond_to do |format|
      format.html { redirect_to cartoleiros_url, notice: "Cartoleiro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartoleiro
      @cartoleiro = Cartoleiro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cartoleiro_params
      params.require(:cartoleiro).permit(:time, :nome, :camisa)
    end
end

app/controllers/pontuacaos_controller.rb
class PontuacaosController < ApplicationController
  before_action :set_pontuacao, only: %i[ show edit update destroy ]

  skip_before_action  :verify_authenticity_token
  
  # GET /pontuacaos or /pontuacaos.json
  def index
    @pontuacaos = Pontuacao.all
  end

  # GET /pontuacaos/1 or /pontuacaos/1.json
  def show
  end

  # GET /pontuacaos/new
  def new
    @pontuacao = Pontuacao.new
  end

  # GET /pontuacaos/1/edit
  def edit
  end

  # POST /pontuacaos or /pontuacaos.json
  def create
    @pontuacao = Pontuacao.new(pontuacao_params)

    respond_to do |format|
      if @pontuacao.save
        format.html { redirect_to pontuacao_url(@pontuacao), notice: "Pontuacao was successfully created." }
        format.json { render :show, status: :created, location: @pontuacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pontuacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontuacaos/1 or /pontuacaos/1.json
  def update
    respond_to do |format|
      if @pontuacao.update(pontuacao_params)
        format.html { redirect_to pontuacao_url(@pontuacao), notice: "Pontuacao was successfully updated." }
        format.json { render :show, status: :ok, location: @pontuacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pontuacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontuacaos/1 or /pontuacaos/1.json
  def destroy
    @pontuacao.destroy

    respond_to do |format|
      format.html { redirect_to pontuacaos_url, notice: "Pontuacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pontuacao
      @pontuacao = Pontuacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pontuacao_params
      params.require(:pontuacao).permit(:cartoleiro_id, :rodada_id, :pontos, :posicao)
    end
end

app/controllers/rodadas_controller.rb
class RodadasController < ApplicationController
  before_action :set_rodada, only: %i[ show edit update destroy ]

  skip_before_action  :verify_authenticity_token

  # GET /rodadas or /rodadas.json
  def index
    @rodadas = Rodada.all
    @cartoleiros = Cartoleiro.all
  end

  # GET /rodadas/1 or /rodadas/1.json
  def show
  end

  # GET /rodadas/new
  def new
    @rodada = Rodada.new
  end

  # GET /rodadas/1/edit
  def edit
  end

  # POST /rodadas or /rodadas.json
  def create
    @rodada = Rodada.new(rodada_params)

    respond_to do |format|
      if @rodada.save
        format.html { redirect_to rodada_url(@rodada), notice: "Rodada was successfully created." }
        format.json { render :show, status: :created, location: @rodada }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rodada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rodadas/1 or /rodadas/1.json
  def update
    respond_to do |format|
      if @rodada.update(rodada_params)
        format.html { redirect_to rodada_url(@rodada), notice: "Rodada was successfully updated." }
        format.json { render :show, status: :ok, location: @rodada }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rodada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rodadas/1 or /rodadas/1.json
  def destroy
    @rodada.destroy

    respond_to do |format|
      format.html { redirect_to rodadas_url, notice: "Rodada was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rodada
      @rodada = Rodada.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rodada_params
      params.require(:rodada).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoleiros_helper.rb
module CartoleirosHelper
end

app/helpers/pontuacaos_helper.rb
module PontuacaosHelper
end

app/helpers/rodadas_helper.rb
module RodadasHelper
end

app/views/cartoleiros/_cartoleiro.html.erb
<div id="<%= dom_id cartoleiro %>">
  <p>
    <strong>Time:</strong>
    <%= cartoleiro.time %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= cartoleiro.nome %>
  </p>

  <p>
    <strong>Camisa:</strong>
    <%= cartoleiro.camisa %>
  </p>

</div>

app/views/cartoleiros/_form.html.erb
<%= form_with(model: cartoleiro) do |form| %>
  <% if cartoleiro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cartoleiro.errors.count, "error") %> prohibited this cartoleiro from being saved:</h2>

      <ul>
        <% cartoleiro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time, style: "display: block" %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :camisa, style: "display: block" %>
    <%= form.check_box :camisa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cartoleiros/edit.html.erb
<h1>Editing Cartoleiro</h1>

<%= render "form", cartoleiro: @cartoleiro %>

<br>

<div>
  <%= link_to "Show", @cartoleiro %> |
  <%= link_to "Back", cartoleiros_path %>
</div>

app/views/cartoleiros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cartoleiros</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Nome</th>
      <th>Camisa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartoleiros.each do |cartoleiro| %>
      <tr>
        <td><%= cartoleiro.time %></td>
        <td><%= cartoleiro.nome %></td>
        <td><%= cartoleiro.camisa %></td>
        <td><%= link_to 'Show', cartoleiro %></td>
        <td><%= link_to 'Edit', edit_cartoleiro_path(cartoleiro) %></td>
        <td><%= link_to 'Destroy', cartoleiro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New cartoleiro", new_cartoleiro_path %>

app/views/cartoleiros/new.html.erb
<h1>New Cartoleiro</h1>

<%= render "form", cartoleiro: @cartoleiro %>

<br>

<div>
  <%= link_to "Back", cartoleiros_path %>
</div>

app/views/cartoleiros/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <h1><%= "#{@cartoleiro.time} - #{@cartoleiro.nome}" %></h1>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-light h3">
        <th>Rodada</th>
        <th>Classificação</th>
        <th>Pontuação</th>
      </tr>
    </thead>

    <tbody>
      <% @cartoleiro.pontuacaos.sort_by {|obj| obj.rodada_id}.each do |pontuacao| %>
        <tr class="h3">
          <td><%= link_to "#{pontuacao.rodada_id} ª Rodada", rodada_path(pontuacao.rodada_id) %></td>
          <td><%= pontuacao.posicao %>º</td>
          <td><%= number_with_precision pontuacao.pontos, :precision => 2 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <%= line_chart @cartoleiro.pontuacaos.select(:rodada_id, :pontos).sort_by{|obj| obj.rodada_id}.map{|p| ["#{p.rodada_id}ª Rodada", p.pontos]}, height: "600px" %>
  
  <footer class="footer">
    <nav>
      <h4><%= link_to "Back",   root_path %></h4>
    </nav>
  </footer>
</div>

<!--
< render @cartoleiro %>

<div>
  < link_to "Edit this cartoleiro", edit_cartoleiro_path(@cartoleiro) %> |
  < link_to "Back to cartoleiros", cartoleiros_path %>

  < button_to "Destroy this cartoleiro", @cartoleiro, method: :delete %>
</div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apuração da Liga</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fas fa-home"></i>
        <% end %>
      </div>
    </nav>

    <div class="container-lg">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pontuacaos/_form.html.erb
<%= form_with(model: pontuacao) do |form| %>
  <% if pontuacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pontuacao.errors.count, "error") %> prohibited this pontuacao from being saved:</h2>

      <ul>
        <% pontuacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cartoleiro_id, style: "display: block" %>
    <%= form.number_field :cartoleiro_id %>
  </div>

  <div class="field">
    <%= form.label :rodada_id, style: "display: block" %>
    <%= form.number_field :rodada_id %>
  </div>

  <div class="field">
    <%= form.label :pontos, style: "display: block" %>
    <%= form.text_field :pontos %>
  </div>

  <div class="field">
    <%= form.label :posicao, style: "display: block" %>
    <%= form.number_field :posicao %>
  </div>

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/pontuacaos/_pontuacao.html.erb
<td><%= pontuacao.cartoleiro_id %></td>
<td><%= pontuacao.rodada_id %></td>
<td><%= pontuacao.pontos %></td>
<td><%= pontuacao.posicao %></td>
<td><%= link_to 'Show', pontuacao %></td>
<td><%= link_to 'Edit', edit_pontuacao_path(pontuacao) %></td>
<td><%= link_to 'Destroy', pontuacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/pontuacaos/edit.html.erb
<h1>Editing Pontuacao</h1>

<%= render "form", pontuacao: @pontuacao %>

<br>

<div>
  <%= link_to "Show", @pontuacao %> |
  <%= link_to "Back", pontuacaos_path %>
</div>

app/views/pontuacaos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pontuacoes</h1>


<table>
  <thead>
    <tr>
      <th>Cartoleiro</th>
      <th>Rodada</th>
      <th>Pontos</th>
      <th>Posicao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pontuacaos.each do |pontuacao| %>
      <tr id="<%= dom_id pontuacao %>">
        <%= render pontuacao %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pontuacao', new_pontuacao_path %>

app/views/pontuacaos/new.html.erb
<h1>New Pontuacao</h1>

<%= render "form", pontuacao: @pontuacao %>

<br>

<div>
  <%= link_to "Back", pontuacaos_path %>
</div>

app/views/pontuacaos/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>Cartoleiro:</strong>
  <%= @pontuacao.cartoleiro_id %>
</p>

<p>
  <strong>Rodada:</strong>
  <%= @pontuacao.rodada_id %>
</p>

<p>
  <strong>Pontos:</strong>
  <%= @pontuacao.pontos %>
</p>

<p>
  <strong>Posicao:</strong>
  <%= @pontuacao.posicao %>
</p>

<div>
  <%= link_to "Edit", edit_pontuacao_path(@pontuacao) %> |
  <%= link_to "Back", pontuacaos_path %>

  <%= button_to "Destroy", @pontuacao, method: :delete %>
</div>

app/views/rodadas/_form.html.erb
<%= form_with(model: rodada) do |form| %>
  <% if rodada.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rodada.errors.count, "error") %> prohibited this rodada from being saved:</h2>

      <ul>
        <% rodada.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rodadas/edit.html.erb
<h1>Editing Rodada</h1>

<%= render "form", rodada: @rodada %>

<br>

<div>
  <%= link_to "Show", @rodada %> |
  <%= link_to "Back", rodadas_path %>
</div>

app/views/rodadas/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <h1>Classificação Final 2º Turno</h1>
  <h2 class="text-danger">Parabéns, <strong>Raposão 3000</strong>!</h2>
  <h2>Campeão da disputa da camisa da Liga Igreja de Cristo - RMBH!</h2>
  <h2 class="text-danger">Obrigado a todos pela participação! Foi bom demais, e ano que vem tem mais!</h2>
  <h2 class="text-primary">Que o Senhor abençoe a todos!</h2>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-light h3">
        <th>Classificação</th>
        <th>Time</th>
        <th>Disputa a camisa?</th>
        <th>Pontos</th>
      </tr>
    </thead>
  
    <tbody>
      <% @cartoleiros.sort_by{|obj| obj.pontuacaos.to_a.sum(&:pontos)}.reverse.each_with_index do |cartoleiro, index| %>
        <tr class="h3">
          <td><%= index +1 %>º</td>
          <td><%= link_to cartoleiro.time, cartoleiro_path(cartoleiro.id) %></td>
          <td><%= cartoleiro.camisa ? "Sim": "Não"  %></td>
          <td><%= number_with_precision(cartoleiro.pontuacaos.to_a.sum(&:pontos), :precision => 2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  
  <%= line_chart @cartoleiros.map{|ct|{name: ct.time, data: ct.pontuacaos.sort_by{|r| r[:rodada_id] }.map{|p| ["#{p.rodada_id}ª Rodada", p.pontos]}}}, height: "800px" %>
  
</div>


<br>

app/views/rodadas/new.html.erb
<h1>New rodada</h1>

<%= render "form", rodada: @rodada %>

<br>

<div>
  <%= link_to "Back", rodadas_path %>
</div>

app/views/rodadas/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <h1><%= @rodada.nome %></h1>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-light h3">
        <th>Classificação</th>
        <th>Time</th>
        <th>Disputa a camisa?</th>
        <th>Pontos</th>
      </tr>
    </thead>
  
    <tbody>
      
      <% @rodada.pontuacaos.sort_by {|obj| obj.posicao}.each do |pontuacao| %>
        <tr class="h3">
          <td><%= pontuacao.posicao %>º</td>
          <td><%= link_to pontuacao.cartoleiro.time, cartoleiro_path(pontuacao.cartoleiro.id) %></td>
          <td><%= pontuacao.cartoleiro.camisa ? "Sim": "Não"  %></td>
          <td><%= number_with_precision pontuacao.pontos, :precision => 2 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  
  <%= column_chart @rodada.pontuacaos.sort_by{|obj| obj.rodada_id}.map{|p| [p.cartoleiro.time, p.pontos]}, height: "600px" %>
  
</div>


<!--
<div>
  < link_to "Edit this rodada", edit_rodada_path(@rodada) %> |
  < link_to "Back to rodadas", rodadas_path %>

  < button_to "Destroy this rodada", @rodada, method: :delete %>
</div>
-->